const logo_path = <T extends string>(logo: T) => `logos/${logo}.svg` as const;

export const logos = {
	android_studio: logo_path('android_studio'),
	astro: logo_path('astro'),
	bootstrap: logo_path('bootstrap'),
	bulma: logo_path('bulma'),
	bun: logo_path('bun'),
	css: logo_path('css'),
	dart: logo_path('dart'),
	datagrip: logo_path('datagrip'),
	docker: logo_path('docker'),
	elysiajs: logo_path('elysiajs'),
	email: logo_path('email'),
	esbuild: logo_path('esbuild'),
	expressjs: logo_path('expressjs'),
	figma: logo_path('figma'),
	flutter: logo_path('flutter'),
	git: logo_path('git'),
	github: logo_path('github'),
	go: logo_path('go'),
	html: logo_path('html'),
	javascript: logo_path('javascript'),
	mariadb: logo_path('mariadb'),
	mongodb: logo_path('mongodb'),
	mysql: logo_path('mysql'),
	nginx: logo_path('nginx'),
	nodejs: logo_path('nodejs'),
	npm: logo_path('npm'),
	parcel: logo_path('parcel'),
	php: logo_path('php'),
	postgresql: logo_path('postgresql'),
	python: logo_path('python'),
	react: logo_path('react'),
	redis: logo_path('redis'),
	rust: logo_path('rust'),
	scss: logo_path('scss'),
	sketch: logo_path('sketch'),
	svelte: logo_path('svelte'),
	swift: logo_path('swift'),
	tailwindcss: logo_path('tailwindcss'),
	typescript: logo_path('typescript'),
	vite: logo_path('vite'),
	vscode: logo_path('vscode'),
	vue: logo_path('vue'),
	webpack: logo_path('webpack'),
	xcode: logo_path('xcode'),
} as const;
